=== magicprogramer/os455/xml/xsd/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="phones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="phone">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="type" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="region" type="xs:string" />
                                        <xs:element name="city" type="xs:string" />
                                        <xs:element name="country" type="xs:string" />
                                        <xs:element name="building_number" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" use="required" />
                        <xs:attribute name="e-mail" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== magicprogramer/os455/xml/xsd/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="employee.css"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="employee.xsd">

<employee name ="ahmed" e-mail = "ahmed@gmail.com" >
    <phones>
    <phone type = "home">
    01226723732
    </phone>
    </phones>
    <address>
    <region>
        middle east
    </region>
    <city>
    alex
    </city>
    <country>
    Egypt
    </country>
    <building_number>
    
    22
    </building_number>
    </address>

</employee>

<employee name ="ahmed" e-mail = "ahmed@gmail.com" >
    <phones>
    <phone type = "home">
    01326723732
    </phone>
    </phones>
    <address>
    <region>
        middle east
    </region>
    <city>
    cairo
    </city>
    <country>
    Egypt
    </country>
    <building_number>
    
    12
    </building_number>
    </address>

</employee>

</employees>
